{
  "formatVersion": "1.1",
  "component": {
    "group": "io.deepmedia.tools",
    "module": "grease",
    "version": "0.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "grease-0.3.7.jar",
          "url": "grease-0.3.7.jar",
          "size": 233274,
          "sha512": "2e55b0658fe987c3f0fe18365a80e3bffd5c31635a68b5bdc1d06ae36045df3e91c6c45c17bc0ee40f17c48f260bf6c3d7de85fb8579630c8ec97d4144191bb2",
          "sha256": "a2aae86cd1eb77773b8ea068981f8101507278559f9d8717e09ea9e113d14c9c",
          "sha1": "84a9b2b7bc1e3a5793a25d12dffdb0912f4955f7",
          "md5": "1cc1f11de224129b9f7b8bbe43360427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "shadow-gradle-plugin",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.1.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.1.4"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        }
      ],
      "files": [
        {
          "name": "grease-0.3.7.jar",
          "url": "grease-0.3.7.jar",
          "size": 233274,
          "sha512": "2e55b0658fe987c3f0fe18365a80e3bffd5c31635a68b5bdc1d06ae36045df3e91c6c45c17bc0ee40f17c48f260bf6c3d7de85fb8579630c8ec97d4144191bb2",
          "sha256": "a2aae86cd1eb77773b8ea068981f8101507278559f9d8717e09ea9e113d14c9c",
          "sha1": "84a9b2b7bc1e3a5793a25d12dffdb0912f4955f7",
          "md5": "1cc1f11de224129b9f7b8bbe43360427"
        }
      ]
    }
  ]
}
