{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rivchain",
    "module": "libsodium-java",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libsodium-java-1.0.0.jar",
          "url": "libsodium-java-1.0.0.jar",
          "size": 104853,
          "sha512": "934e499b35dec53c943658e8520a7bd3358b1711fed863c6524c55b56150f38ab673a989822868e4dda1f9e07e6dc2a6fc9c74ccb395c3731c71988887c9ca18",
          "sha256": "dbaeff84e2f09dc905396c69438e8f7c8e6b076e3e1f743abe1d2ebc3b999a39",
          "sha1": "f834c4246533668e8af7ef1ade2e4925d0e87c38",
          "md5": "d0bc27c3206741a3ffa3fa9e0654470a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.18.0"
          }
        },
        {
          "group": "com.goterl",
          "module": "resource-loader",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "libsodium-java-1.0.0.jar",
          "url": "libsodium-java-1.0.0.jar",
          "size": 104853,
          "sha512": "934e499b35dec53c943658e8520a7bd3358b1711fed863c6524c55b56150f38ab673a989822868e4dda1f9e07e6dc2a6fc9c74ccb395c3731c71988887c9ca18",
          "sha256": "dbaeff84e2f09dc905396c69438e8f7c8e6b076e3e1f743abe1d2ebc3b999a39",
          "sha1": "f834c4246533668e8af7ef1ade2e4925d0e87c38",
          "md5": "d0bc27c3206741a3ffa3fa9e0654470a"
        }
      ]
    }
  ]
}
