{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rivchain",
    "module": "libsodium-java",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libsodium-java-2.0.0.jar",
          "url": "libsodium-java-2.0.0.jar",
          "size": 104671,
          "sha512": "32d5bf853373bee48116e8dc071f808564f64c838393112b6ebf702ce1f7a33bbfa71322db70e5eda41c911993c03dbe76019be7925d880bdc1ff38cc78c2256",
          "sha256": "19981c47029cb56f87707e885739c9e8d1841f00ffbef6245f8a681604dc6846",
          "sha1": "e623c064195baface9b82fbb564074b84c60ecd1",
          "md5": "3acb137f7ee2ca58e5116bf663a7f6a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.18.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.goterl",
          "module": "resource-loader",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libsodium-java-2.0.0.jar",
          "url": "libsodium-java-2.0.0.jar",
          "size": 104671,
          "sha512": "32d5bf853373bee48116e8dc071f808564f64c838393112b6ebf702ce1f7a33bbfa71322db70e5eda41c911993c03dbe76019be7925d880bdc1ff38cc78c2256",
          "sha256": "19981c47029cb56f87707e885739c9e8d1841f00ffbef6245f8a681604dc6846",
          "sha1": "e623c064195baface9b82fbb564074b84c60ecd1",
          "md5": "3acb137f7ee2ca58e5116bf663a7f6a4"
        }
      ]
    }
  ]
}
