{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rivchain",
    "module": "libsodium-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0.aar",
          "url": "libsodium-android-1.0.0.aar",
          "size": 89013,
          "sha512": "3bbe57329f364358edd4464e3b3e2f7a54cd846523e5d788426b60f34a183dc5b86e81b0e2ca86ba696e67380ea88244901f1f7868079e7744c3430b75b32db3",
          "sha256": "4acd1e8b6868df0427526332f3817d492620c0cf5aacd3e2083075c033598f83",
          "sha1": "1e804335d2753a2445e737a3e03c35738b8af4ea",
          "md5": "0adb2604068a4cc124f86435c1ec8e5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.18.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "libsodium-android-1.0.0.aar",
          "url": "libsodium-android-1.0.0.aar",
          "size": 89013,
          "sha512": "3bbe57329f364358edd4464e3b3e2f7a54cd846523e5d788426b60f34a183dc5b86e81b0e2ca86ba696e67380ea88244901f1f7868079e7744c3430b75b32db3",
          "sha256": "4acd1e8b6868df0427526332f3817d492620c0cf5aacd3e2083075c033598f83",
          "sha1": "1e804335d2753a2445e737a3e03c35738b8af4ea",
          "md5": "0adb2604068a4cc124f86435c1ec8e5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0-sources.jar",
          "url": "libsodium-android-1.0.0-sources.jar",
          "size": 2746,
          "sha512": "57edc696c6187bf80550c381531860ff8ac574feb2bbffc3effe32a13593d1c525be88e2bbe461355d47b96592b90258dfe344c21ff53f5e9396f91b153b28b0",
          "sha256": "81211993d7a518a85176b3d38a6107ddab77e46b1e670024626878779ca54dab",
          "sha1": "5ab605f51b75f21595ec90332d564f670c222f3b",
          "md5": "63f3d86ba91dfc4467cd78c2d10d2c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0-javadoc.jar",
          "url": "libsodium-android-1.0.0-javadoc.jar",
          "size": 292663,
          "sha512": "7affe6e5ff87333f08b23419eb2ddc2df6e4e4c121b3a8528d60b0b3d588c86fb0148d369a293c18962d5042cb9440c890a0e6b459ff39d3beb3c3cbd080c18b",
          "sha256": "0d9e7ac31c60e4b35693455dc3acabaec87710a283958c4653978e005b35a393",
          "sha1": "4f32e1988384f6c47b972afa8ecf1158edd00d6e",
          "md5": "3970ea9b35a446bb690c2b69e9e94c64"
        }
      ]
    }
  ]
}
