{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rivchain",
    "module": "libsodium-android",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0.aar",
          "url": "libsodium-android-1.0.0.aar",
          "size": 89012,
          "sha512": "c95bc0b9a5322b890d299db9ad98696ad57d016a4af3e69d3db243f62354c56f4f8b05519fe5796c0ea9804f415fe908a71cbce2e52bbb6677d50947168dd85c",
          "sha256": "d15150471af936a711e68437e96a73e52665dbb10dd2cb833ab7b8cdfebc9102",
          "sha1": "02d04a83de562a75fbc393e78b3331bc857a4a80",
          "md5": "6c0cffeb8472e857c245f8007c444599"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.18.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "libsodium-android-1.0.0.aar",
          "url": "libsodium-android-1.0.0.aar",
          "size": 89012,
          "sha512": "c95bc0b9a5322b890d299db9ad98696ad57d016a4af3e69d3db243f62354c56f4f8b05519fe5796c0ea9804f415fe908a71cbce2e52bbb6677d50947168dd85c",
          "sha256": "d15150471af936a711e68437e96a73e52665dbb10dd2cb833ab7b8cdfebc9102",
          "sha1": "02d04a83de562a75fbc393e78b3331bc857a4a80",
          "md5": "6c0cffeb8472e857c245f8007c444599"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0-sources.jar",
          "url": "libsodium-android-1.0.0-sources.jar",
          "size": 2746,
          "sha512": "57edc696c6187bf80550c381531860ff8ac574feb2bbffc3effe32a13593d1c525be88e2bbe461355d47b96592b90258dfe344c21ff53f5e9396f91b153b28b0",
          "sha256": "81211993d7a518a85176b3d38a6107ddab77e46b1e670024626878779ca54dab",
          "sha1": "5ab605f51b75f21595ec90332d564f670c222f3b",
          "md5": "63f3d86ba91dfc4467cd78c2d10d2c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libsodium-android-1.0.0-javadoc.jar",
          "url": "libsodium-android-1.0.0-javadoc.jar",
          "size": 292663,
          "sha512": "7affe6e5ff87333f08b23419eb2ddc2df6e4e4c121b3a8528d60b0b3d588c86fb0148d369a293c18962d5042cb9440c890a0e6b459ff39d3beb3c3cbd080c18b",
          "sha256": "0d9e7ac31c60e4b35693455dc3acabaec87710a283958c4653978e005b35a393",
          "sha1": "4f32e1988384f6c47b972afa8ecf1158edd00d6e",
          "md5": "3970ea9b35a446bb690c2b69e9e94c64"
        }
      ]
    }
  ]
}
